### ISSUE TITLE
1.2.0: TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by pmowrer** [ben-eb/postcss-minify-params#4]
Hi there!

Sorry for not being able to provide much context, but it seems that 1.2.0 broke our build. We don't depend directly on `postcss-minify-params`, but rather indirectly via some other PostCSS dependency (I assumed `postcss-loader`, but I don't see a direct dependency in its `package.json`).

The error occurs compiling Angular Material's main scss (which is massive, making it hard to pin-point the problem). But it appears possible that the updated walk algorithm in 1.2.0 isn't entirely safe.

Our PostCSS tool chain includes:
`postcss-cssnext`,
`postcss-import`,
`postcss-loader`,
`postcss-reporter`,
`precss`
... all of which were updated to their latest version, but the problem persisted.

```bash
ERROR in ./~/css-loader!./~/postcss-loader?pack=sass!./~/sass-loader!./~/material.scss
Module build failed: TypeError: Cannot read property 'value' of undefined
at /node_modules/postcss-minify-params/dist/index.js:61:38
at walk (/node_modules/postcss-value-parser/lib/walk.js:15:13)
at ValueParser.walk (/node_modules/postcss-value-parser/lib/index.js:18:5)
at /node_modules/postcss-minify-params/dist/index.js:56:20
at /node_modules/postcss/lib/container.js:296:28
at /node_modules/postcss/lib/container.js:148:26
at Root.each (/node_modules/postcss/lib/container.js:114:22)
at Root.walk (/node_modules/postcss/lib/container.js:147:21)
at Root.walkAtRules (/node_modules/postcss/lib/container.js:294:25)
at /node_modules/postcss-minify-params/dist/index.js:49:13
at LazyResult.run (/node_modules/postcss/lib/lazy-result.js:276:20)
at /node_modules/postcss/lib/lazy-result.js:190:37
at LazyResult.asyncTick (/node_modules/postcss/lib/lazy-result.js:204:15)
at /node_modules/postcss/lib/lazy-result.js:202:27
at LazyResult.asyncTick (/node_modules/postcss/lib/lazy-result.js:204:15)
at /node_modules/postcss/lib/lazy-result.js:202:27
at LazyResult.asyncTick (/node_modules/postcss/lib/lazy-result.js:204:15)
at /node_modules/postcss/lib/lazy-result.js:202:27
at LazyResult.asyncTick (/node_modules/postcss/lib/lazy-result.js:204:15)
at /node_modules/postcss/lib/lazy-result.js:202:27
at LazyResult.asyncTick (/node_modules/postcss/lib/lazy-result.js:204:15)
at /node_modules/postcss/lib/lazy-result.js:202:27
at LazyResult.asyncTick (/node_modules/postcss/lib/lazy-result.js:204:15)
at /node_modules/postcss/lib/lazy-result.js:202:27
at LazyResult.asyncTick (/node_modules/postcss/lib/lazy-result.js:204:15)
at /node_modules/postcss/lib/lazy-result.js:202:27
at LazyResult.asyncTick (/node_modules/postcss/lib/lazy-result.js:204:15)
at /node_modules/postcss/lib/lazy-result.js:202:27
at LazyResult.asyncTick (/node_modules/postcss/lib/lazy-result.js:204:15)
at /node_modules/postcss/lib/lazy-result.js:202:27
at LazyResult.asyncTick (/node_modules/postcss/lib/lazy-result.js:204:15)
at /node_modules/postcss/lib/lazy-result.js:195:31
at run (/node_modules/karma/node_modules/core-js/modules/es6.promise.js:87:22)
at /node_modules/karma/node_modules/core-js/modules/es6.promise.js:100:28
at flush (/node_modules/karma/node_modules/core-js/modules/_microtask.js:18:9)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)

@ ./~/material.scss 4:14-159
```

**Comment by ben-eb** [comment]
Hi @pmowrer,

Perhaps you have an at-rule with an empty set of parentheses? I don't think we should throw an error here though, it should pass through.

**Comment by tehmoon** [comment]
Hi @ben-eb,

It broke our CI too! ping @davey-h
```Module build failed: TypeError: Cannot read property 'value' of undefined
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss-minify-params/dist/index.js:61:38
    at walk (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss-value-parser/lib/walk.js:15:13)
    at ValueParser.walk (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss-value-parser/lib/index.js:18:5)
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss-minify-params/dist/index.js:56:20
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/container.js:296:28
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/container.js:148:26
    at Root.each (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/container.js:147:21)
    at Root.walkAtRules (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/container.js:294:25)
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss-minify-params/dist/index.js:49:13
    at LazyResult.run (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:276:20)
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:190:37
    at LazyResult.asyncTick (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:204:15)
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:202:27
    at LazyResult.asyncTick (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:204:15)
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:202:27
    at LazyResult.asyncTick (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:204:15)
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:202:27
    at LazyResult.asyncTick (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:204:15)
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:202:27
    at LazyResult.asyncTick (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:204:15)
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:202:27
    at LazyResult.asyncTick (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:204:15)
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:202:27
    at LazyResult.asyncTick (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:204:15)
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:202:27
    at LazyResult.asyncTick (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:204:15)
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:202:27
    at LazyResult.asyncTick (/private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:204:15)
    at /private/var/preveil-deploy/buildbot/osxslave/osxbuild_core/build/frontend/node_modules/postcss/lib/lazy-result.js:195:31```

**Comment by ben-eb** [comment]
@pmowrer @tehmoon,

I've pushed `1.2.1` that should resolve this issue. Can you confirm, please?

**Comment by tehmoon** [comment]
@ben-eb Wow thxs for the quick answer! I should be able to tell you that in 2-3 mins

**Comment by kayneb** [comment]
I hit this too. Thanks for the quick fix!

**Comment by tehmoon** [comment]
@ben-eb it worked!!!  Thank you for being so quick to fix it!

**Comment by ben-eb** [comment]
Thanks guys, I'll mark this as resolved. 👍 

Perhaps removing empty function parentheses should also be done here? If anyone would like to share where these are occurring in their builds (and if they should be removed) please let me know.

I'm pretty sure that `@media () {}` is equivalent to `@media {}` but I didn't want to investigate this whilst the module was throwing.

**Comment by psimyn** [comment]
@ben-eb we were using it for firefox styles. For this at least they don't seem equivalent:

This CSS results in blue background in firefox.
```
@-moz-document url-prefix() {
  select {
    background: blue;
  }
}

@-moz-document url-prefix {
  select {
    background: red;
  }
}

```

thanks for the quick bugfix!

**Comment by ben-eb** [comment]
@psimyn Thanks for the info! 😄
